<?php
defined('ABSPATH') || exit;

add_action('acf/init', function () {
    if (!function_exists('acf_add_local_field_group')) {
        return;
    }

    acf_add_local_field_group([
        'key'    => 'group_venza_producto_home',
        'title'  => 'Producto - Home de Productos',
        'fields' => [
            [
                'key'           => 'field_venza_producto_destacado_home',
                'label'         => 'Producto destacado en /productos/',
                'name'          => 'producto_destacado_home',
                'type'          => 'true_false',
                'ui'            => 1,
                'default_value' => 0,
            ],
            [
                'key'           => 'field_venza_producto_home_subtitulo',
                'label'         => 'Subtitulo principal',
                'name'          => 'producto_home_subtitulo',
                'type'          => 'text',
                'instructions'  => 'Ejemplo: Crema Humectante',
            ],
            [
                'key'           => 'field_venza_producto_home_banner_imagen',
                'label'         => 'Banner principal de /productos/',
                'name'          => 'producto_home_banner_imagen',
                'type'          => 'image',
                'return_format' => 'id',
                'preview_size'  => 'medium',
                'library'       => 'all',
            ],
            [
                'key'           => 'field_venza_producto_home_beneficio_1',
                'label'         => 'Beneficio 1 (titulo)',
                'name'          => 'producto_home_beneficio_1',
                'type'          => 'text',
            ],
            [
                'key'           => 'field_venza_producto_home_beneficio_1_imagen',
                'label'         => 'Beneficio 1 (imagen)',
                'name'          => 'producto_home_beneficio_1_imagen',
                'type'          => 'image',
                'return_format' => 'id',
                'preview_size'  => 'medium',
                'library'       => 'all',
            ],
            [
                'key'           => 'field_venza_producto_home_beneficio_1_texto',
                'label'         => 'Beneficio 1 (texto inferior)',
                'name'          => 'producto_home_beneficio_1_texto',
                'type'          => 'text',
            ],
            [
                'key'           => 'field_venza_producto_home_beneficio_2',
                'label'         => 'Beneficio 2 (titulo)',
                'name'          => 'producto_home_beneficio_2',
                'type'          => 'text',
            ],
            [
                'key'           => 'field_venza_producto_home_beneficio_2_imagen',
                'label'         => 'Beneficio 2 (imagen)',
                'name'          => 'producto_home_beneficio_2_imagen',
                'type'          => 'image',
                'return_format' => 'id',
                'preview_size'  => 'medium',
                'library'       => 'all',
            ],
            [
                'key'           => 'field_venza_producto_home_beneficio_2_texto',
                'label'         => 'Beneficio 2 (texto inferior)',
                'name'          => 'producto_home_beneficio_2_texto',
                'type'          => 'text',
            ],
            [
                'key'           => 'field_venza_producto_home_beneficio_3',
                'label'         => 'Beneficio 3 (titulo)',
                'name'          => 'producto_home_beneficio_3',
                'type'          => 'text',
            ],
            [
                'key'           => 'field_venza_producto_home_beneficio_3_imagen',
                'label'         => 'Beneficio 3 (imagen)',
                'name'          => 'producto_home_beneficio_3_imagen',
                'type'          => 'image',
                'return_format' => 'id',
                'preview_size'  => 'medium',
                'library'       => 'all',
            ],
            [
                'key'           => 'field_venza_producto_home_beneficio_3_texto',
                'label'         => 'Beneficio 3 (texto inferior)',
                'name'          => 'producto_home_beneficio_3_texto',
                'type'          => 'text',
            ],
            [
                'key'           => 'field_venza_producto_home_desc_texto',
                'label'         => 'Texto seccion descripcion',
                'name'          => 'producto_home_descripcion_texto',
                'type'          => 'wysiwyg',
                'tabs'          => 'visual',
                'toolbar'       => 'basic',
                'media_upload'  => 0,
            ],
            [
                'key'           => 'field_venza_producto_home_desc_imagen',
                'label'         => 'Imagen seccion descripcion',
                'name'          => 'producto_home_descripcion_imagen',
                'type'          => 'image',
                'return_format' => 'id',
                'preview_size'  => 'medium',
                'library'       => 'all',
            ],
            [
                'key'           => 'field_venza_producto_home_claim_texto',
                'label'         => 'Texto caja destacada',
                'name'          => 'producto_home_claim_texto',
                'type'          => 'textarea',
                'rows'          => 3,
                'instructions'  => 'Texto descriptivo de la caja redondeada.',
            ],
            [
                'key'           => 'field_venza_producto_home_claim_cta',
                'label'         => 'Texto fuerte caja destacada',
                'name'          => 'producto_home_claim_cta',
                'type'          => 'text',
                'instructions'  => 'Ejemplo: Pruebalo hoy mismo.',
            ],
            [
                'key'           => 'field_venza_producto_home_disponibilidad',
                'label'         => 'Disponible en (override)',
                'name'          => 'producto_home_disponibilidad_override',
                'type'          => 'text',
                'instructions'  => 'Opcional. Si se deja vacio, usa los paises por defecto.',
            ],
            [
                'key'           => 'field_venza_producto_home_mas_subtitulo',
                'label'         => 'Subtitulo de Mas productos',
                'name'          => 'producto_home_mas_productos_subtitulo',
                'type'          => 'text',
                'instructions'  => 'Ejemplo: Jabon antibacterial',
            ],
            [
                'key'           => 'field_venza_producto_single_gradient_color',
                'label'         => 'Color del degrade (pagina producto)',
                'name'          => 'producto_single_gradient_color',
                'type'          => 'color_picker',
                'default_value' => '#acdcef',
                'instructions'  => 'Color inicial del degrade horizontal en descripcion y tamanos.',
            ],
            [
                'key'           => 'field_venza_producto_single_gradient_end_color',
                'label'         => 'Color final del degrade (pagina producto)',
                'name'          => 'producto_single_gradient_end_color',
                'type'          => 'color_picker',
                'default_value' => '#ffffff',
                'instructions'  => 'Color final del degrade horizontal en la seccion de descripcion.',
            ],
            [
                'key'           => 'field_venza_producto_single_tamanos_gradient_color',
                'label'         => 'Color del degrade (bloque tamanos)',
                'name'          => 'producto_single_tamanos_gradient_color',
                'type'          => 'color_picker',
                'default_value' => '#acdcef',
                'instructions'  => 'Color inicial del degrade del bloque de tamanos. Si se deja vacio, usa el color general de pagina producto.',
            ],
            [
                'key'           => 'field_venza_producto_single_tamanos_gradient_end_color',
                'label'         => 'Color final del degrade (bloque tamanos)',
                'name'          => 'producto_single_tamanos_gradient_end_color',
                'type'          => 'color_picker',
                'default_value' => '#ffffff',
                'instructions'  => 'Color final del degrade del bloque de tamanos. Si se deja vacio, usa el color final de pagina producto.',
            ],

            // Campos editables del producto interno (single)
            [
                'key'           => 'field_venza_producto_single_banner_imagen',
                'label'         => 'Hero interno - Banner',
                'name'          => 'producto_single_banner_imagen',
                'type'          => 'image',
                'return_format' => 'id',
                'preview_size'  => 'medium',
                'library'       => 'all',
                'instructions'  => 'Imagen principal del hero interno del producto.',
            ],
            [
                'key'          => 'field_venza_producto_single_claim_texto',
                'label'        => 'Hero interno - Texto destacado',
                'name'         => 'producto_single_claim_texto',
                'type'         => 'textarea',
                'instructions' => 'Texto corto sobre el banner del hero interno. Usa Enter para partirlo en dos lineas si el producto lo necesita.',
                'rows'         => 2,
                'new_lines'    => '',
            ],
            [
                'key'           => 'field_venza_producto_single_intro_imagen',
                'label'         => 'Hero interno - Imagen destacada del producto',
                'name'          => 'producto_single_intro_imagen',
                'type'          => 'image',
                'return_format' => 'id',
                'preview_size'  => 'medium',
                'library'       => 'all',
                'instructions'  => 'Imagen grande del producto en la seccion de identidad.',
            ],
            [
                'key'           => 'field_venza_producto_single_descripcion_imagen',
                'label'         => 'Seccion descripcion - Imagen',
                'name'          => 'producto_single_descripcion_imagen',
                'type'          => 'image',
                'return_format' => 'id',
                'preview_size'  => 'medium',
                'library'       => 'all',
                'instructions'  => 'Imagen lateral de la seccion de descripcion interna.',
            ],
            [
                'key'           => 'field_venza_producto_single_descripcion_texto',
                'label'         => 'Seccion descripcion - Texto',
                'name'          => 'producto_single_descripcion_texto',
                'type'          => 'wysiwyg',
                'tabs'          => 'visual',
                'toolbar'       => 'basic',
                'media_upload'  => 0,
                'instructions'  => 'Texto principal de la seccion de descripcion del producto.',
            ],
            [
                'key'           => 'field_venza_producto_single_tamano_1_imagen',
                'label'         => 'Tamanos - Imagen 1',
                'name'          => 'producto_single_tamano_1_imagen',
                'type'          => 'image',
                'return_format' => 'id',
                'preview_size'  => 'medium',
                'library'       => 'all',
                'instructions'  => 'Primera imagen de la seccion de tamanos.',
            ],
            [
                'key'          => 'field_venza_producto_single_tamano_1_nombre',
                'label'        => 'Tamanos - Nombre 1',
                'name'         => 'producto_single_tamano_1_nombre',
                'type'         => 'text',
                'instructions' => 'Ejemplo: Individual',
            ],
            [
                'key'          => 'field_venza_producto_single_tamano_1_descripcion',
                'label'        => 'Tamanos - Descripcion 1',
                'name'         => 'producto_single_tamano_1_descripcion',
                'type'         => 'text',
                'instructions' => 'Ejemplo: 110g',
            ],
            [
                'key'          => 'field_venza_producto_single_tamano_1_nota',
                'label'        => 'Tamanos - Nota 1',
                'name'         => 'producto_single_tamano_1_nota',
                'type'         => 'text',
                'instructions' => 'Opcional',
            ],
            [
                'key'           => 'field_venza_producto_single_tamano_2_imagen',
                'label'         => 'Tamanos - Imagen 2',
                'name'          => 'producto_single_tamano_2_imagen',
                'type'          => 'image',
                'return_format' => 'id',
                'preview_size'  => 'medium',
                'library'       => 'all',
                'instructions'  => 'Segunda imagen de la seccion de tamanos.',
            ],
            [
                'key'          => 'field_venza_producto_single_tamano_2_nombre',
                'label'        => 'Tamanos - Nombre 2',
                'name'         => 'producto_single_tamano_2_nombre',
                'type'         => 'text',
                'instructions' => 'Ejemplo: 3 pack 330g',
            ],
            [
                'key'          => 'field_venza_producto_single_tamano_2_descripcion',
                'label'        => 'Tamanos - Descripcion 2',
                'name'         => 'producto_single_tamano_2_descripcion',
                'type'         => 'text',
                'instructions' => 'Ejemplo: 3 barras de 110g',
            ],
            [
                'key'          => 'field_venza_producto_single_tamano_2_nota',
                'label'        => 'Tamanos - Nota 2',
                'name'         => 'producto_single_tamano_2_nota',
                'type'         => 'text',
                'instructions' => 'Opcional',
            ],
            [
                'key'           => 'field_venza_producto_single_tamano_3_imagen',
                'label'         => 'Tamanos - Imagen 3',
                'name'          => 'producto_single_tamano_3_imagen',
                'type'          => 'image',
                'return_format' => 'id',
                'preview_size'  => 'medium',
                'library'       => 'all',
                'instructions'  => 'Tercera imagen de la seccion de tamanos.',
            ],
            [
                'key'          => 'field_venza_producto_single_tamano_3_nombre',
                'label'        => 'Tamanos - Nombre 3',
                'name'         => 'producto_single_tamano_3_nombre',
                'type'         => 'text',
                'instructions' => 'Ejemplo: 4 pack 440g',
            ],
            [
                'key'          => 'field_venza_producto_single_tamano_3_descripcion',
                'label'        => 'Tamanos - Descripcion 3',
                'name'         => 'producto_single_tamano_3_descripcion',
                'type'         => 'text',
                'instructions' => 'Ejemplo: 4 barras de 110g',
            ],
            [
                'key'          => 'field_venza_producto_single_tamano_3_nota',
                'label'        => 'Tamanos - Nota 3',
                'name'         => 'producto_single_tamano_3_nota',
                'type'         => 'text',
                'instructions' => 'Opcional',
            ],
        ],
        'location' => [
            [
                [
                    'param'    => 'post_type',
                    'operator' => '==',
                    'value'    => 'producto',
                ],
            ],
        ],
        'position' => 'normal',
        'style'    => 'default',
    ]);
});
